### ISSUE TITLE
Fazer merge da develop com a master

### ISSUE THREAD

**Issue by SilvaRamon** [aqueledorme/jokenpo#1]
A ideia é fazer o merge da branch develop para a branch master, para aprendizado de como fazer um merge no Git.

Passos:

- Estando na branch **develop**, fazer checkout na branch **master**.

- Fazer git merge com a branch **develop**. EX: `git merge develop` e `git push`

- Criar nova tag. EX: `git tag -a v2.0 -m "versão javascript"` e `git push --tags`

@lostgame12

**Comment by SilvioCarlos12** [comment]
Concluido
